Feature/contact edit
scbd/kronos-web pull request #54
Opened 2020-07-30 13:57 UTC by JamesSCBD

2020-07-30 22:04 UTC, sbilodeau commented on pages/contacts/_edit.vue
> +    updatedOn() { return `${date(this.contact.updatedOn)} by ${this.contact.updatedBy}`; },
Don't built stirng in js. bette to put this in the HTML part and user `| datetime filter 
```
{{contact.updatedOn | datetime}} by {{contact.updatedBy}}
```

2020-07-30 22:09 UTC, sbilodeau commented on pages/contacts/_edit.vue
> +    removeEmailCcField,
I think there is a ways to simplify by creating a component for repeated values.

2020-07-30 22:10 UTC, sbilodeau commented on pages/contacts/_edit.vue
> +    removeEmailCcField,
where you pass the validation method and the error text

2020-07-31 12:15 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +    updatedOn() { return `${date(this.contact.updatedOn)} by ${this.contact.updatedBy}`; },
Done! Information shown in input box but now remove input box and use as simple text

2020-07-31 12:18 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +    removeEmailCcField,
Done! create a component for repeated fields and implement validation in component

2021-01-19 23:32 UTC, sbilodeau requested changes

2021-01-20 13:27 UTC, JamesSCBD commented on components/controls/RepeatedFormInput.vue
> +    const re = /^\+\d+\s/;
DONE! Changes done as suggested.

2021-01-20 13:27 UTC, JamesSCBD commented on components/controls/RepeatedFormInput.vue
> +}
DONE! Changes done as suggested.

2021-01-20 13:27 UTC, JamesSCBD commented on components/list/ContactsList.vue
> +  console.log(item);
DONE! removed debug code.

2021-01-20 13:28 UTC, JamesSCBD commented on components/list/ContactsList.vue
> +  this.$router.push(`contacts/${item.contactId}`);
DONE! Changes done as suggested and removed debug code

2021-01-20 13:28 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +              </p>
DONE! Changes done as suggested.

2021-01-20 13:28 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +                      label="Primary Email Address"
DONE! Changes done as suggested.

2021-01-20 13:29 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +                    />
DONE! Changes done as suggested.

2021-01-20 13:29 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +                  <button type="button" class="btn btn-primary" @click="copyToClipboard">
DONE! Changes done as suggested.

2021-01-20 13:30 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +  { value: 'Prof.', text: 'Prof.' },
DONE! Changes done as suggested.

2021-01-20 13:30 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +}
DONE! Changes done as suggested.

2021-01-20 13:31 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +    lastNameRequired() { return this.contact.lastName !== ''; },
DONE! Suggested change will not work so I have applied below change instead:

`firstNameRequired() { return (this.contact.firstName || '').trim() !== ''; },
 lastNameRequired() { return (this.contact.lastName || '').trim() !== ''; },`

2021-01-20 13:32 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +    countyRequired() { return !this.contact.country && !this.contact.isUseOrganizationAddress; },
DONE! Corrected spell

2021-01-20 14:01 UTC, sbilodeau commented on pages/contacts/_edit.vue
> +    lastNameRequired() { return this.contact.lastName !== ''; },
ok. sorry I miss typeed. you could have use double! 
eg: ``` !!(this.contact.firstName || '').trim() ```

2021-01-20 14:16 UTC, sbilodeau requested changes

2021-01-20 14:16 UTC, sbilodeau commented on components/controls/RepeatedFormInput.vue
> +            + ' Example: +1 514 288-2220 ext 221';
putting text in the code is not good, especially for translation of the interface. but it's ok for now

2021-01-20 14:16 UTC, sbilodeau commented on filters/contactNumbers.js
> +export { isContactNumberValid };
`contact` number dosen't mean anything. rename `function` and `file` to `Phone` number

2021-01-20 14:16 UTC, sbilodeau commented on pages/contacts/_edit.vue
> +    lastNameRequired() { return (this.contact.lastName || '').trim() !== ''; },
FirstName and LastName are always required. I think the field are badly named. 
```suggestion
    firstNameValid() { return (this.contact.firstName || '').trim() !== ''; },
    lastNameValid() { return (this.contact.lastName || '').trim() !== ''; },
```

2021-01-20 14:16 UTC, sbilodeau commented on pages/contacts/_edit.vue
> +  this.$router.go(-1);
Going Back is what the implementation do, the behaviour. The operation is Cancel the edit. Please Rename to `cancel`

```suggestion
function cancel() {
  this.$router.go(-1);
```

2021-01-20 14:24 UTC, sbilodeau requested changes
We have a standard naming convention:
`load()` // load record from api
`save()` // create / update record
`close()` // close/cancel edit without or after saving

2021-01-20 14:24 UTC, sbilodeau commented on pages/contacts/_edit.vue
> +async function contactUpdate(event) {
We have standard naming convention. please rename to `save`
```suggestion
async function save(event) {
```

2021-01-20 14:24 UTC, sbilodeau commented on pages/contacts/_edit.vue
> +}
we have standard naming convention. Please extract a `load` function.

```suggestion
async function mounted() {
  await load();
}

async function load() {
  const result = await this.$kronosApi.getContact(this.contactId);
  this.contact = result;
  //TODO this.originalContact = cone of result;
}
```

2021-01-21 11:00 UTC, JamesSCBD commented on filters/contactNumbers.js
> +export { isContactNumberValid };
DONE ! renamed contact to phone.

2021-01-21 11:01 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +    lastNameRequired() { return (this.contact.lastName || '').trim() !== ''; },
DONE ! renamed name as suggested

2021-01-21 11:01 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +  this.$router.go(-1);
DONE ! renamed name as suggested

2021-01-21 11:01 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +async function contactUpdate(event) {
DONE ! renamed name as suggested

2021-01-21 11:01 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +}
DONE ! changes done as suggested.

2021-01-21 11:16 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +                  v-model="contact.isUseOrganizationAddress"
DONE ! changes done as suggested.

2021-01-22 07:38 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +}
DONE! changes done as suggested.

2021-01-22 08:13 UTC, JamesSCBD commented on pages/contacts/_edit.vue
> +                        <CountrySelector v-model="contact.country" :multiple="false" :disabled="contact.isUseOrganizationAddress" />
DONE! changes done as suggested.

2021-01-22 22:26 UTC, sbilodeau commented on components/list/ContactsList.vue
> +  this.$router.push(`organizations/${encodeURIComponent(item.organization.organizationId)}/contacts/${encodeURIComponent(item.contactId)}`);
Can you replace instead of pushing? (prevent back button to work an fall in an infinite loop)

2021-01-22 22:28 UTC, sbilodeau commented on components/list/columns/MemberCount.vue
> +      </a>
put the url instead of a click 
```html
<a :href="/organizations/${encodeURIComponent(this.organization.organizationId)}/contacts/new"> ...
```

2021-01-22 23:04 UTC, sbilodeau requested changes
We are almost there.

there is a strange behaviour, clicking the cancel button save the record

2021-01-22 23:04 UTC, sbilodeau commented on pages/organizations/_organizationId/contacts/_contactId.vue
> +      this.emailRequired = true;
make emailRequired as computed propterty:

```javascript
computed: {
   emailRequired () { return !this.originalContact.contactId || !!this.originalContact.emails.length
}
```

2021-01-24 10:57 UTC, JamesSCBD commented on components/list/columns/MemberCount.vue
> +      </a>
DONE! changes done as suggested.

2021-01-24 10:57 UTC, JamesSCBD commented on components/list/columns/MemberCount.vue
> +}
DONE! changes done as suggested. 
Cancel button save issue fixed.

2021-01-24 10:58 UTC, JamesSCBD commented on components/list/columns/Organization.vue
> +      </a>
DONE! changes done as suggested.

2021-01-24 10:58 UTC, JamesSCBD commented on components/list/columns/Organization.vue
> +}
DONE! changes done as suggested.

2021-01-24 10:58 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId.vue
> +      </CAlert>
DONE! changes done as suggested.

2021-01-24 10:59 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId.vue
> +  }
DONE! changes done to improve readability of code. Let me know if it require some more changes.

2021-01-24 11:00 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId.vue
> +      this.emailRequired = true;
DONE! changes done as suggested.

2021-01-25 13:59 UTC, sbilodeau commented on api/kronos.js
> +    const data = await this.http.post(`api/v2018/organizations/${encodeURIComponent(contact.organizationId)}/contacts`, { json: contact }).json();
please passe the `organizationId` as 1st parameter,  `contact.organizationId ` is not a field of contact update
```suggestion
  async createContact(organizationId, contact) {
    const data = await this.http.post(`api/v2018/organizations/${encodeURIComponent(organizationId)}/contacts`, { json: contact }).json();
```

2021-01-27 02:09 UTC, sbilodeau approved these changes

2021-01-27 02:09 UTC, merged