Prevent Navigation Component
scbd/kronos-web pull request #64
Opened 2021-01-29 12:10 UTC by JamesSCBD

Prevent navigation component created initially.

2021-02-01 12:09 UTC, sbilodeau requested changes
Prevent Navigation have no binding to `beforeunload` or `beforeRouteLeave` event. 
how the modal is supposed to appears and prevent route change or navigation?

2021-02-01 12:09 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +  },
watch deep is an heavy operation. maybe a good approach would be to create a `isDirty` computer prop that return if the form us dirt
```javascript
isDirty() {
 this.dirty = this.dirty || JSON.stringify(original) != JSON.stringify(current);
 return this.dirty;
}
```

2021-02-01 12:09 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +
this is wrong. you don't need to reset the usless `prevent` field. base the enabling of the component on the `isDirty` then use `next()` if you wnt to porceed with route change. isDirty (prevent) must remain if use stay on the page

2021-02-01 12:09 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +    });
drop
```suggestion
    this.$nextTick(() => {
      this.dirty = false;
    });
```

2021-02-01 12:22 UTC, sbilodeau commented on components/navigation/PreventNavigation.vue
> +      :show.sync="prevent"
this is wrong

2021-02-02 06:06 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +          <slot name="header" />
DONE! changes done as suggested

2021-02-02 06:07 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +      </template>
DONE! changes done as suggested. Moved body part after header.

2021-02-02 06:07 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +    },
DONE! removed prop title

2021-02-02 06:07 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +        return arr.length > 0 && arr.every((action) => action.text && action.name);
DONE! changes done as suggested

2021-02-02 06:09 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +      dirty: false,
DONE! made isDirty computed property.

2021-02-02 06:09 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +      prevent       : false,
DONE! used isDirty flag to pass in prevent.

2021-02-02 06:10 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +  },
DONE! changes done as suggested. Code is quite different (removed this.dirty usage)

2021-02-02 06:12 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +
DONE! please check the current changes. removed this.prevent code from here.

2021-02-02 06:12 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +    });
DONE! dropped the code as we made isDirty as computed property

2021-02-02 06:13 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +      :show.sync="prevent"
DONE! remove prevent usage in show/hide. created inner variable isOpen in prevent-navigation to show hide it.

2021-02-02 07:21 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +  setTimeout(() => {
Hi @sbilodeau, I have checked that update:show event is only firing when close-on-backdrop prop is true and modal closes on any outside click. So, I think this event will not help.

Currently when I directly focus on action, it is not happening because after focus modal is opening so focus is moving to the modal div.

So, now I have changed the code and opened modal before focus. and focus on action after modal reders.(means used nextTick())

2021-02-02 10:23 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +        </template>
DONE! changes done as suggested.

2021-02-02 10:23 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +        </template>
DONE! changes done as suggested.

2021-02-02 11:58 UTC, sbilodeau requested changes

2021-02-02 11:58 UTC, sbilodeau commented on components/navigation/PreventNavigation.vue
> +  this.$emit(name, this.routeParams);
Better to clone the object reference to avoid parent/child manipulation
```suggestion
  const params = {...this.routeParams }
  this.$emit(name, params);
```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +async function save() {
I suggest to pass a default refreshUrl=true value and refresh the url only if true. So on prevent nav you can avoit
```javascript
async function save(refreshUrl=true) {
...
  if(refreshUrl) this.refreshUrl(result);
...
}

2021-02-02 11:58 UTC, sbilodeau commented on components/navigation/PreventNavigation.vue
> +    });
We used => to save this closure. pass parameters `beforeRouteChange` it  transparently wrpapped)
```suggestion
    const unregister = this.$router.beforeEach((to, from, next) => { // arrow function to save `this` closure reference
      beforeRouteChange.call(this, to, from, next);
    });
```

2021-02-02 11:58 UTC, sbilodeau commented on components/navigation/PreventNavigation.vue
> +    },
Extract from `methods` block and rename to `preventSystemNavgation`

2021-02-02 11:58 UTC, sbilodeau commented on components/navigation/PreventNavigation.vue
> +      routeParams: {
rename to `nextRouteParams`

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +        @next="handleNext"
you can simply call $event.next()
```suggestion
        @next="$event.next()"
```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +        @cancel="handleCancel"
better to call next(false)
```suggestion
        @cancel="$event.next(false)"
```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +        { text: 'Cancel', name: 'cancel' },
align code. make them all one line or all expanded
```suggestion
        { name: 'save',   text: 'Save',       type: 'primary',  default: true },
        { name: 'next'    text: "Don't save", type: 'danger' },
        { name: 'cancel', text: 'Cancel' },
```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +    isDirty() { return JSON.stringify(this.originalContact) !== JSON.stringify(this.contact); },
align code with above computed props

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +  this.originalContact = this.contact;
I suggest to let the system decide. 
```suggestion
```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +        @next="handleNext"
```suggestion
        @next="$event.next()"
```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +        @cancel="handleCancel"
```suggestion
        @cancel="$event.next(false)"
```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +      ],
align code

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +
You can drop
```suggestion

function handleNext({ next }) {
  next();
}

function handleCancel() {
  // handle cancel
}

```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +
you can drop
```suggestion

function handleNext({ next }) {
  next();
}

function handleCancel() {
  // handle cancel
}

```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +  this.originalOrganization = this.organization;
let system decide
```suggestion
  // to make isDirty flag false when moving back to previous url
  this.originalOrganization = this.organization;
```

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +      await load.call(this);
why reload? save `result` already contains the record;

2021-02-02 11:58 UTC, sbilodeau commented on pages/organizations/_organizationId/index.vue
> +async function save() {
whle function can be simplified and use refreshUrl default param


```javascript
async function save(refreshUrl=true) {
  try {
    const form = this.$refs.organizationForm;

    if (!form.checkValidity()) return;

    const { organization }   = this;
    const { organizationId } = organization;

    const result = !organizationId
      ? await this.$kronosApi.createOrganization(organization)
      : await this.$kronosApi.updateOrganization(organization);

    this.$toast.success(`${result.acronym || result.name} saved!`);

    this.organization         = result;
    this.originalOrganization = _.cloneDeep(result);

    if (!organizationId && refreshUrl) {
      this.refreshUrl(result);
    }
  } catch (error) {
    // give Good alert of incorrect id
    this.$toast.error(error.messsage || `TODO: error ${error}`);
  }
}
```

2021-02-02 12:57 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +  this.$emit(name, this.routeParams);
DONE! changes done as suggested.

2021-02-02 12:57 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +async function save() {
DONE! changes done as suggested.

2021-02-02 12:57 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +    });
DONE! changes done as suggested.

2021-02-02 12:57 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +    },
DONE! changes done as suggested.

2021-02-02 12:58 UTC, JamesSCBD commented on components/navigation/PreventNavigation.vue
> +      routeParams: {
DONE! changes done as suggested.

2021-02-02 12:58 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +        @next="handleNext"
DONE! changes done as suggested.

2021-02-02 12:58 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +        @cancel="handleCancel"
DONE! changes done as suggested.

2021-02-02 12:58 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +        { text: 'Cancel', name: 'cancel' },
DONE! changes done as suggested.

2021-02-02 12:58 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +    isDirty() { return JSON.stringify(this.originalContact) !== JSON.stringify(this.contact); },
DONE! changes done as suggested.

2021-02-02 12:58 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +  this.originalContact = this.contact;
DONE! changes done as suggested.

2021-02-02 12:59 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +        @next="handleNext"
DONE! changes done as suggested.

2021-02-02 12:59 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +        @cancel="handleCancel"
DONE! changes done as suggested.

2021-02-02 12:59 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +      ],
DONE! changes done as suggested.

2021-02-02 12:59 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +
DONE! changes done as suggested.

2021-02-02 12:59 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +
DONE! changes done as suggested.

2021-02-02 12:59 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +  this.originalOrganization = this.organization;
DONE! changes done as suggested.

2021-02-02 12:59 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +      await load.call(this);
DONE! changes done as suggested.

2021-02-02 13:00 UTC, JamesSCBD commented on pages/organizations/_organizationId/index.vue
> +async function save() {
DONE! changes done as suggested.

2021-02-02 15:52 UTC, sbilodeau approved these changes

2021-02-02 15:53 UTC, merged