Use Store Actions - Initial Version
scbd/kronos-web pull request #67
Opened 2021-02-04 12:55 UTC by JamesSCBD

1. Written store actions (contact - initial, organization - partial)
2. used store actions in reference files

2021-02-04 14:46 UTC, sbilodeau requested changes
Take adavanage of the `allowRreadFromCache` in code when relevant

2021-02-04 14:46 UTC, sbilodeau commented on components/list/OrganizationsList.vue
> +    const result               = await this.queryOrganizations({ ...query, limit: 5 });
I think the name of the function above it wrong. shoulf be `getSelectedOrganizationsResult` instead of `getSelectedContactsResult`

2021-02-04 14:46 UTC, sbilodeau commented on components/controls/selectors/OrganizationContactSelector.vue
> +  const contacts      = this.disabled ? [] : await this.getOrganizationContacts(this.organizationId);
shoudl pass useCache=true
```suggestion
  const contacts      = this.disabled ? [] : await this.getOrganizationContacts(this.organizationId, true);
```

2021-02-04 14:46 UTC, sbilodeau commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +    const organization = await this.getOrganization(organizationId);
can read from cache
```suggestion
    const organization = await this.getOrganization(organizationId, true);
```

2021-02-04 14:46 UTC, sbilodeau commented on store/contacts.js
> +    return _.cloneDeep(contacts);
no need to clone I think. contact is not from cache object

2021-02-04 14:46 UTC, sbilodeau commented on store/contacts.js
> +    return _.cloneDeep(contact);
no need to clone I think

2021-02-04 14:46 UTC, sbilodeau commented on store/contacts.js
> +    // commit('UPDATE_ORGANIZATION_CONTACTS_CACHE', result.organizationId, result,
drop organization-contacts cache

2021-02-04 14:46 UTC, sbilodeau commented on store/contacts.js
> +    return _.cloneDeep(result);
no need to clone

2021-02-04 14:46 UTC, sbilodeau commented on store/contacts.js
> +    return _.cloneDeep(result);
non need to clone

2021-02-04 14:46 UTC, sbilodeau commented on store/organizations.js
> +
us array as you suggested
make `100` a constante at the top of the file.

2021-02-04 14:46 UTC, sbilodeau commented on store/organizations.js
> +    return _.cloneDeep(organization);
missing allowReadFromCache=false
```suggestion
  async getOrganizationById({ commit, getters }, id, allowReadFromCache=false) {
    let organization = null

    if (allowReadFromCache && getters.isOrganizationCached(id)) {
      organization = getters.getOrganizationById(id);
    } else {
      organization = await this.$kronosApi.getOrganization(id);
      if (organization) commit(UPDATE_CACHE, [ organization ]);
    }

    return _.cloneDeep(organization);
```

2021-02-04 14:46 UTC, sbilodeau commented on store/organizations.js
> +    let organization = {};
default value must be `null` not an `empty object`;

2021-02-04 14:46 UTC, sbilodeau commented on store/organizations.js
> +      commit(UPDATE_CACHE, [ result ]);
I think `UPDATE_CACHE` should also do the `UPDATE_TO_SELECTION`

2021-02-05 07:57 UTC, JamesSCBD commented on components/list/OrganizationsList.vue
> +    const result               = await this.queryOrganizations({ ...query, limit: 5 });
DONE! changes done as suggested.

2021-02-05 07:58 UTC, JamesSCBD commented on components/controls/selectors/OrganizationContactSelector.vue
> +  const contacts      = this.disabled ? [] : await this.getOrganizationContacts(this.organizationId);
DONE! changes done as suggested. passed parameter in one object form. as store actions take parameter in single object.

2021-02-05 07:58 UTC, JamesSCBD commented on pages/organizations/_organizationId/contacts/_contactId/index.vue
> +    const organization = await this.getOrganization(organizationId);
DONE! changes done as suggested.

2021-02-05 07:58 UTC, JamesSCBD commented on store/contacts.js
> +    return _.cloneDeep(contacts);
DONE! changes done as suggested.

2021-02-05 07:58 UTC, JamesSCBD commented on store/contacts.js
> +    return _.cloneDeep(contact);
DONE! changes done as suggested.

2021-02-05 07:59 UTC, JamesSCBD commented on store/contacts.js
> +    return _.cloneDeep(result);
DONE! changes done as suggested.

2021-02-05 07:59 UTC, JamesSCBD commented on store/contacts.js
> +    return _.cloneDeep(result);
DONE! changes done as suggested.

2021-02-05 07:59 UTC, JamesSCBD commented on store/organizations.js
> +
DONE! changes done as suggested.

2021-02-05 07:59 UTC, JamesSCBD commented on store/organizations.js
> +    return _.cloneDeep(organization);
DONE! changes done as suggested.

2021-02-05 08:00 UTC, JamesSCBD commented on store/organizations.js
> +    let organization = {};
DONE! changes done as suggested.

2021-02-05 10:04 UTC, JamesSCBD commented on store/contacts.js
> +    // commit('UPDATE_ORGANIZATION_CONTACTS_CACHE', result.organizationId, result,
Hi @sbilodeau, currently I don't think that we need to drop organization-contacts at the time of adding/updating contact of organization. So, I have updated organization-cache when any contacts is added/updated.

2021-02-06 11:40 UTC, JamesSCBD commented on store/organizations.js
> +      commit(UPDATE_CACHE, [ result ]);
DONE! changes done as suggested. UPDATE_CACHE will update all organization related cache and REMOVE_CACHE will remove all organization related cache

2021-02-08 01:42 UTC, sbilodeau requested changes
Remove Organization cahce update to simple "drop" as proposed in the card.
The implementation is too compleax an I saw many flaws already and many other possible one. Also code was too complexe

Follow requirement in method signature from trello card:

required: 
```javascript
getOrganizationContacts (id, allowCache=false) ///with default value param for allowCache
```

but you implemented:
```javascript
 getOrganizationContacts ({id, allowCache}) //passing object instead of params, require to pass object everywhere insteadOf normal call with 'optional' paramter
```

2021-02-08 01:42 UTC, sbilodeau commented on store/contacts.js
> +
why? 
if you have nothing to commit than you don't commit anything 

Delete this mutation please.

2021-02-08 01:42 UTC, sbilodeau commented on store/contacts.js
> +    commit(NO_ACTION);
If you have nothing to commit then you don't commit anything.

Probably you should update cache with returned objects instead. no?,

2021-02-08 01:42 UTC, sbilodeau commented on store/contacts.js
> +    commit(NO_ACTION);
You should update cache / selections with the new fresh returned object.

don't commit nothing. this trigger useless app refresh

2021-02-08 01:42 UTC, sbilodeau commented on store/organizations.js
> +    _.forEach(organizations, (organization) => {
you can also use native forEach of javascript array
```suggestion
    organizations.forEach((organization) => {
```

2021-02-08 01:42 UTC, sbilodeau commented on store/organizations.js
> +      }
remove this if condition there. you cannot pass and array without organization inside. this check prevent good code elsewhere

add separate validation check at line 30 that test that the passed array !=null * evry value are valid. if not throw error.

eg: line 30
```javascript
// 1st line of the Methods (line 30)
const isValid = organizations && organizations.every((o)=> o && o.orgnizationId);
if(!isValid) throw Error("organizations list is invalid");
```

then do operations

 ```suggestion
      const index = state.selectedOrganizations.findIndex((o) => o.organizationId === organization.organizationId);
      if (index >= 0) state.selectedOrganizations.splice(index, 1, organization);
```

2021-02-08 01:42 UTC, sbilodeau commented on store/organizations.js
> +  [UPDATE_ORGANIZATION_CONTACTS_CACHE](state, { organizationId, contacts, contact }) {
The current implementation is way too complex for nothing.

why having two non exclusive parameters???  I did not read it all I was lost after two lines

switch back to initial idea: Drop cached value

And only allow params: `organizationId` (madatory)  && `contacts` (null/array);

```javascript 
organizationContactCache = organizationContactCache.filter(o=>o.organizationId!=organizationId) //Systematically drop org

if(contacts) { //
  organizationContactCache.push({organizationId, contacts}) // add at the end
}

while (organizationContactCache.length> MAX_ORGANIZATION_CONTACT_CACHE) // keep only maz size latest orgs
  organizationContactCache.shift() // remove 1st element in the array
```

 

if(

2021-02-08 01:42 UTC, sbilodeau commented on store/organizations.js
> +  async getOrganization({ commit, getters }, { id, allowReadFromCache }) {
Change method signature for the one specified int the trello card.
Using two parameters. not an object 
```suggestion
  async getOrganization({ commit, getters },  id, allowReadFromCache=false) {
```

2021-02-08 01:42 UTC, sbilodeau commented on store/organizations.js
> +  async getOrganizationContacts({ commit, getters }, { id, allowReadFromCache }) {
Change method signature for the one specified int the trello card.
Using two parameters and default value. not an object
```suggestion
  async getOrganizationContacts({ commit, getters }, id, allowReadFromCache=false) {
```

2021-02-08 01:42 UTC, sbilodeau commented on store/organizations.js
> +  },
Drop this mutation and use UPDATE_ORGANIZATION_CONTACTS_CACHE({ organizationId, contacts=null})

2021-02-08 01:42 UTC, sbilodeau commented on store/organizations.js
> +    commit(UPDATE_ORGANIZATION_CONTACTS_CACHE, { organizationId: id, contacts });
Only update cache if read from api
```suggestion
    let contacts = null
    
    if(allowReadFromCache && getters.isOrganizationContactsCached(id) {
      contacts = getters.getOrganizationContacts(id)
    } else {
      contacts = await this.$kronosApi.getOrganizationContacts(id);
      commit(UPDATE_ORGANIZATION_CONTACTS_CACHE, { organizationId: id, contacts });
    }
```

2021-02-08 05:57 UTC, JamesSCBD commented on store/contacts.js
> +
this is because I don't know how to disable eslint for paticular line. I was facing error because we don't want to use commit in method and 1st argument is required for context so....

2021-02-08 09:31 UTC, JamesSCBD commented on store/contacts.js
> +
Deleted unwanted mutation (NO_ACTION)

2021-02-08 09:56 UTC, JamesSCBD commented on store/organizations.js
> +  async getOrganizationContacts({ commit, getters }, { id, allowReadFromCache }) {
Hi @sbilodeau, 

Actually vuex action will only accept two parameters... One is context and second is payload... 

if we pass more parameters we will get undefined value of those parameters... 

So, I have passed it as a object.

2021-02-08 10:03 UTC, JamesSCBD commented on store/contacts.js
> +    commit(NO_ACTION);
Removed NO_ACTION mutation

2021-02-08 10:04 UTC, JamesSCBD commented on store/contacts.js
> +    commit(NO_ACTION);
Removed NO_ACTION mutation, and commited UPDATE_CACHE.

2021-02-08 10:05 UTC, JamesSCBD commented on store/organizations.js
> +    _.forEach(organizations, (organization) => {
Used native foreach

2021-02-08 10:07 UTC, JamesSCBD commented on store/organizations.js
> +      }
Hi @sbilodeau, Added separate validation and removed loop. 

Had done this because we don't require to loop through organizations array twice (One for validate, one for actual operation).

2021-02-08 10:08 UTC, JamesSCBD commented on store/organizations.js
> +  [UPDATE_ORGANIZATION_CONTACTS_CACHE](state, { organizationId, contacts, contact }) {
Dropped organization cache at time of add/update/delete contact

2021-02-08 10:12 UTC, JamesSCBD commented on store/organizations.js
> +  },
Dropped mutation and used suggested mutation

2021-02-08 10:12 UTC, JamesSCBD commented on store/organizations.js
> +    commit(UPDATE_ORGANIZATION_CONTACTS_CACHE, { organizationId: id, contacts });
DONE! changes done as suggested

2021-02-09 23:24 UTC, sbilodeau commented on store/organizations.js
> +  async getOrganizationContacts({ commit, getters }, { id, allowReadFromCache }) {
ok

2021-02-09 23:49 UTC, merged