Nuxt-Auth - initial commit
scbd/kronos-web pull request #69
Opened 2021-02-09 16:20 UTC by JamesSCBD

1. Installed nuxt-auth on primary level
2. login page created - partial
3. removed scbd-auth - partial - not sure

2021-02-09 23:51 UTC, sbilodeau commented on layouts/default.vue
> +    <div v-if="!$auth.user.isAuthenticated" class="col-md-12">
good value is:
```javascript
$auth.loggedIn
```
https://auth.nuxtjs.org/api/auth#loggedin

2021-02-10 00:00 UTC, sbilodeau requested changes
Good start

Use @nuxtjs/auth-next v5 instead of ~@nuxtjs/auth v4.~

2021-02-10 00:00 UTC, sbilodeau commented on layouts/default.vue
>      if (!isAuthenticated) return this.$router.push({ path: '/login' });
this will not bee needed anymore. you will make nuxt-auth global and the config will redirect user to login page automatically

2021-02-10 00:00 UTC, sbilodeau commented on layouts/login.vue
> +  const isAuthenticated = true;
```javascript
this.$auth.loggedIn
```

2021-02-10 00:00 UTC, sbilodeau commented on middleware/auth.js
> +// const routeRoles = ({ route }) => (route.matched[0] ?
delete this file

2021-02-10 00:00 UTC, sbilodeau commented on package.json
> +    "@nuxtjs/axios": "^5.13.1",
use @nuxtjs/auth-next v5 instead with a fixed version

https://auth.nuxtjs.org/status#nuxtjsauth-next-v5

2021-02-10 10:22 UTC, JamesSCBD commented on layouts/default.vue
>      if (!isAuthenticated) return this.$router.push({ path: '/login' });
DONE! removed it

2021-02-10 10:23 UTC, JamesSCBD commented on layouts/login.vue
> +  const isAuthenticated = true;
DONE!

2021-02-10 10:23 UTC, JamesSCBD commented on middleware/auth.js
> +// const routeRoles = ({ route }) => (route.matched[0] ?
DONE! deleted file

2021-02-10 10:23 UTC, JamesSCBD commented on package.json
> +    "@nuxtjs/axios": "^5.13.1",
DONE!

2021-02-10 13:41 UTC, sbilodeau requested changes
Minor changes

2021-02-10 13:41 UTC, sbilodeau commented on components/kronos/header/DropdownAccnt.vue
> +  this.$store.dispatch('clear');
please use mapAction instead of dispatch

2021-02-10 13:41 UTC, sbilodeau commented on layouts/default.vue
> +    const initOrganizations = this.$store.dispatch('organizations/initialize');
use mapActions

2021-02-10 13:41 UTC, sbilodeau commented on layouts/login.vue
> +  if (this.$auth.loggedIn) return this.$router.push({ path: '/' });
Drop. login page `auth:'guest'` is doing this job

2021-02-10 13:41 UTC, sbilodeau commented on nuxt.config.js
> +import toast from './configs/toast';
align `from` clause  with the ones above

2021-02-10 13:41 UTC, sbilodeau commented on pages/login.vue
> +    this.$toast.error('Incorrect Credentials!');
Can you also show/add a `warning` alert box into the form?  Below *Forget Password* [Login] button

---------------
Email
[ ]
Password
[ ]
Forget Password?    [Login]
>  **Login failed** 
> The email address and password combination you entered is incorrect.
---------------

clear it when login() is trigger OR after 5 seconds, using the automatic CAlert timer of `show = 5`.

https://coreui.io/vue/docs/components/alert.html


Alose change toast text
```suggestion
    this.$toast.error('The email address and password combination you entered is incorrect');
```

2021-02-10 14:31 UTC, JamesSCBD commented on components/kronos/header/DropdownAccnt.vue
> +  this.$store.dispatch('clear');
DONE!

2021-02-10 14:31 UTC, JamesSCBD commented on layouts/default.vue
> +    const initOrganizations = this.$store.dispatch('organizations/initialize');
DONE!

2021-02-10 14:31 UTC, JamesSCBD commented on layouts/login.vue
> +  if (this.$auth.loggedIn) return this.$router.push({ path: '/' });
DONE!

2021-02-10 14:31 UTC, JamesSCBD commented on nuxt.config.js
> +import toast from './configs/toast';
DONE!

2021-02-10 14:32 UTC, JamesSCBD commented on pages/login.vue
> +    this.$toast.error('Incorrect Credentials!');
DONE!

2021-02-10 19:43 UTC, sbilodeau approved these changes

2021-02-10 19:45 UTC, merged