Roles - Initial start
scbd/kronos-web pull request #75
Opened 2021-02-22 14:39 UTC by JamesSCBD

2021-02-24 05:48 UTC, sbilodeau requested changes
Please delete old set of roles
Implement left menu security
make sure you check security for batch tasks. I cannot see it

2021-02-24 05:48 UTC, sbilodeau commented on middleware/roles.js
> +  if (roles === []) return;
this is wrong.
two arrays cannot be ===

```
[] === [] => false!!!
```

you have to test: isEmptyor lenght==0

2021-02-24 05:48 UTC, sbilodeau commented on pages/contacts/index.vue
> +  roles  : [ ...Administrators, ...UsersCanRead ],
onle is enough: UsersCanRead already contains admins'

2021-02-24 05:48 UTC, sbilodeau commented on pages/forbidden.vue
> +  roles: [ ...Anyone ],
no. use `auth:false` instead

2021-02-24 05:55 UTC, JamesSCBD commented on middleware/roles.js
> +  if (roles === []) return;
yes true... my bad.

2021-02-24 15:10 UTC, sbilodeau requested changes

2021-02-25 03:58 UTC, JamesSCBD commented on configs/roles.js
> +export const MeetingNominators = [ 'Kronos-FullAccess', 'Kronos-User', 'Kronos-Meeting-Nominator' ];
DONE!

2021-02-25 03:58 UTC, JamesSCBD commented on middleware/roles.js
> +  if (roles === []) return;
DONE!

2021-02-25 03:58 UTC, JamesSCBD commented on pages/contacts/index.vue
> +  roles  : [ ...Administrators, ...UsersCanRead ],
DONE!

2021-02-25 03:58 UTC, JamesSCBD commented on pages/forbidden.vue
> +  roles: [ ...Anyone ],
DONE!

2021-02-25 03:59 UTC, JamesSCBD commented on components/kronos/sidebar/Nav.vue
> +    <CSidebarNavItem v-if="accessibleRoutes.includes('index')" name="Dashbord" icon="tachometerAlt" @click.native="redirect('index')" />
DONE!

2021-02-25 03:59 UTC, JamesSCBD commented on components/kronos/sidebar/Nav.vue
> +  this.accessibleRoutes = await getAccessibleRoutes.call(this, pageRoutes);
DONE!

2021-02-25 03:59 UTC, JamesSCBD commented on components/list/columns/MemberCount.vue
> +    },
DONE!

2021-02-25 03:59 UTC, JamesSCBD commented on components/list/columns/MemberCount.vue
> +    <div v-if="addAccess" class="col-4 text-center">
DONE!

2021-02-25 03:59 UTC, JamesSCBD commented on components/list/columns/MemberCount.vue
> +    <div class="text-center" :class="addAccess ? 'col-6': 'col-12'">
DONE!

2021-02-25 04:00 UTC, JamesSCBD commented on middleware/roles.js
> +export default ({ route, $auth, redirect }) => {
DONE!

2021-02-25 04:00 UTC, JamesSCBD commented on pages/organizations/index.vue
> +  this.$router.push({ name: 'organizations-organizationId', params: { organizationId } });
DONE!

2021-02-25 23:18 UTC, merged