Timezone selector added
scbd/kronos-web pull request #82
Opened 2021-03-02 10:24 UTC by JamesSCBD

2021-03-02 12:04 UTC, sbilodeau requested changes

2021-03-02 12:04 UTC, sbilodeau commented on package.json
> +    "tzdata": "1.0.25",
exceptionally  use ~ in version so timezones will upgrade on deploy (last number, 25, 26, 27...)

```suggestion
    "tzdata": "~1.0.25",
```

2021-03-03 05:28 UTC, JamesSCBD commented on components/controls/selectors/TimezoneSelector.vue
> +    selectedTimezone: { get() { return this.value; }, set(value) { this.$emit('input', (value || '')); } },
DONE!

2021-03-03 05:28 UTC, JamesSCBD commented on components/controls/selectors/TimezoneSelector.vue
> +      default : '',
DONE!

2021-03-03 05:28 UTC, JamesSCBD commented on components/controls/selectors/TimezoneSelector.vue
> +    timezoneOptions() { return tzdata ? Object.keys(tzdata.zones) : []; },
DONE!

2021-03-03 05:29 UTC, JamesSCBD commented on components/controls/selectors/TimezoneSelector.vue
> +    timezoneOptions() { return tzdata ? Object.keys(tzdata.zones) : []; },
DONE!

2021-03-03 05:29 UTC, JamesSCBD commented on package.json
> +    "tzdata": "1.0.25",
DONE!

2021-03-04 01:17 UTC, sbilodeau approved these changes

2021-03-04 01:17 UTC, merged