datetime selector - initial version
scbd/kronos-web pull request #83
Opened 2021-03-02 10:24 UTC by JamesSCBD

2021-03-02 12:13 UTC, sbilodeau requested changes

2021-03-02 12:13 UTC, sbilodeau commented on components/controls/selectors/DateRangeSelector.vue
> +      placeholder="Select date range"
```suggestion
      placeholder="Select a start and and end date"
```

2021-03-02 12:13 UTC, sbilodeau commented on components/controls/selectors/DateRangeSelector.vue
> +    value: {
values can be `null` at beginning (new record)

2021-03-02 12:13 UTC, sbilodeau commented on components/controls/selectors/TimeSelector.vue
> +      :time-str="['hour', 'min', 'sec']"
I think it's not possible but if yes can you remove second (only if possible)

2021-03-03 05:43 UTC, JamesSCBD commented on components/controls/selectors/DateRangeSelector.vue
> +      placeholder="Select date range"
Hi @sbilodeau, 

I have used secondPlaceholder prop for date range but due to some incorrect usage it is not showing secondPlaceholder correctly

In below code they have used placeholder value in secondPlaceholder: 
https://github.com/livelybone/vue-datepicker/blob/master/src/components/DateRangePicker.vue

So, instead currently I am using placeholder as you suggested.

2021-03-03 05:46 UTC, JamesSCBD commented on components/controls/selectors/DateRangeSelector.vue
> +    value: {
DONE!

2021-03-04 17:46 UTC, sbilodeau requested changes
Please remove the onfocus event that change the imput[type] from text to time/date. I understand the idea but It hides the calendar button to the user and force user to click twice to open calendar for the same operation, which annoying.

2021-03-04 17:46 UTC, sbilodeau commented on components/controls/selectors/DateRangeSelector.vue
> +            onfocusout="(this.type='text')"
remove

2021-03-04 17:46 UTC, sbilodeau commented on components/controls/selectors/DateSelector.vue
> +      onfocusout="(this.type='text')"
remove

2021-03-04 17:46 UTC, sbilodeau commented on components/controls/selectors/TimeSelector.vue
> +      onfocusout="(this.type='text')"
remove

2021-03-04 17:46 UTC, sbilodeau commented on filters/datetime.js
> +}
normally, ISO format can be compared using string representation. 

if you want to compare date then you should pass Date Object or full ISO date instead of string +format

not sure about this function signature.

most probably the best would be to passe ISODate, JSDate or Luxon Datetime to compare. you 

I suggest you yo add a `asDateTime` funciton to simplify date conversion
eg:
https://github.com/scbd/www.cbd.int/blob/master/components/meetings/filters.js#L13

you may support yyyy-MM-dd format (if string match `/^\d{4}-\d{2}-\d{2}$/`. allow asDateTime to be provided with luxon options as 2nd paramaters (eg to pass timezone {zone:'asia/india')

```javascript
export function asDateTime(date, options) {
    if(date instanceof DateTime)  return date
    if(date instanceof Date)      return DateTime.fromJSDate(date, options)
    if(typeof(date) === 'string') {
        if(`/^\d{4}-\d{2}-\d{2}$/`.test(date))
            return DaetTime. fromFormat(date, 'yyy-MM-dd', options)
        return DateTime.fromISO(date, options)
    }
    throw Error('Unknown date/time format');
}
```


then compare dates.

2021-03-04 17:46 UTC, sbilodeau commented on components/controls/selectors/DateRangeSelector.vue
> +            :disabled="disabled"
max should be set to endDate when enddate is selected:

```suggestion
            :disabled="disabled"
            :max="selectedEndDate"
```

2021-03-04 17:46 UTC, sbilodeau commented on components/controls/selectors/DateRangeSelector.vue
> +            :disabled="disabled"
min should be set whe startDate is set
```suggestion
            :disabled="disabled"
            :min="selectedStartDate"
```

2021-03-04 17:57 UTC, sbilodeau requested changes

2021-03-04 17:57 UTC, sbilodeau commented on components/controls/selectors/DateSelector.vue
> +  <div>
please make the input the root element

2021-03-04 17:57 UTC, sbilodeau commented on components/controls/selectors/TimeSelector.vue
> +  <div>
please make input the root element

2021-03-04 17:57 UTC, sbilodeau commented on components/controls/selectors/DateRangeSelector.vue
> +          </div>
why absolute?

template mu be must be sing bootstrap form row I think

https://getbootstrap.com/docs/4.0/components/forms/#form-row

2021-03-05 07:54 UTC, JamesSCBD commented on components/controls/selectors/DateRangeSelector.vue
> +            onfocusout="(this.type='text')"
Removed

2021-03-05 07:54 UTC, JamesSCBD commented on components/controls/selectors/DateSelector.vue
> +      onfocusout="(this.type='text')"
Removed

2021-03-05 07:54 UTC, JamesSCBD commented on components/controls/selectors/TimeSelector.vue
> +      onfocusout="(this.type='text')"
Removed

2021-03-05 07:55 UTC, JamesSCBD commented on filters/datetime.js
> +}
currently added asDateTime function in datetime filters for future use..... but removed compareDates function as it is not required in daterangepicker. checked in chrome, firefox, edge browsers.

2021-03-05 07:55 UTC, JamesSCBD commented on components/controls/selectors/DateRangeSelector.vue
> +            :disabled="disabled"
Done!

2021-03-05 07:55 UTC, JamesSCBD commented on components/controls/selectors/DateRangeSelector.vue
> +            :disabled="disabled"
Done!

2021-03-05 07:55 UTC, JamesSCBD commented on components/controls/selectors/DateSelector.vue
> +  <div>
Done!

2021-03-05 07:56 UTC, JamesSCBD commented on components/controls/selectors/TimeSelector.vue
> +  <div>
Done!

2021-03-05 07:56 UTC, JamesSCBD commented on components/controls/selectors/DateRangeSelector.vue
> +          </div>
used form-row

2021-03-05 14:19 UTC, sbilodeau requested changes

2021-03-05 14:19 UTC, sbilodeau commented on filters/datetime.js
> +  if (value instanceof DateTime)  return value;
If option specify a timezone then set the datetime timezone (setZone)

2021-03-05 15:50 UTC, sbilodeau commented on components/controls/selectors/TimeSelector.vue
> +        && (isValidFormat(value, Formats.HH_MM_SS) || isValidFormat(value, Formats.HH_MM)));
```suggestion
        && Object.values(Formats).some(f=>isValidFormat(value, f)));
```

2021-03-05 15:53 UTC, sbilodeau requested changes

2021-03-05 15:53 UTC, sbilodeau commented on components/controls/selectors/TimeSelector.vue
> +            returnData = returnData.slice(0, returnData.lastIndexOf(':'));
```suggestion
            returnData = returnData.substr(0, Formats.HH_MM.length);
```

2021-03-05 16:06 UTC, merged