do not pass parameter if query value is blank
scbd/kronos-web pull request #89
Opened 2021-03-10 08:56 UTC by JamesSCBD

2021-03-11 01:09 UTC, sbilodeau requested changes

2021-03-11 01:09 UTC, sbilodeau commented on api/kronos.js
> +    if (!value) return;
test if value is undefined instead (===`ubdefined`)

because `false`, `0`, `''` `null` are falsy value that may need to be passed

2021-03-11 12:14 UTC, JamesSCBD commented on api/kronos.js
> +    if (!value) return;
Done!

2021-03-12 13:26 UTC, sbilodeau approved these changes

2021-03-12 13:26 UTC, merged