Online Nomination
scbd/kronos-web pull request #95
Opened 2021-03-17 15:17 UTC by JamesSCBD

1. Basic List created

2021-03-18 21:47 UTC, sbilodeau reviewed
See review comment. 

I suggest to create a new KronosApi instancve where you passs the key for authorization

2021-03-18 21:47 UTC, sbilodeau commented on api/kronos.js
> +    };
I wonder if it wont be better to create a new KronosApi instance in the page and use this special intance instead.

Or make the participant store to use independent KronosApi instance that will load token from query string key of the router 
eg:
```javascript
new KronosApi(()=>`Bearer ${this.$router.query.key}`)

```

2021-03-18 21:47 UTC, sbilodeau commented on components/register/steps/Search.vue
> +          <BFormInput
trigger search on on keyboard return/enter

2021-03-18 21:47 UTC, sbilodeau commented on components/register/steps/Search.vue
> +          <BFormInput
trigger search on on keyboard return/enter

2021-03-18 21:47 UTC, sbilodeau commented on components/register/steps/Search.vue
> +              <CButton v-if="data.item.nominated" color="secondary">
make it `btn-link` style

2021-03-18 21:47 UTC, sbilodeau commented on components/list/ParticipantList.vue
> +        <RegistrationStatusCol v-if="data.item.registrationStatuses" :key="column.key" :registration-status="data.item.registrationStatuses[index] || {}" />
don't use this colum type. iot's for internal use. display registration status same way as original screenshot

2021-03-19 12:45 UTC, JamesSCBD commented on api/kronos.js
> +    };
Done!

2021-03-19 12:46 UTC, JamesSCBD commented on components/register/steps/Search.vue
> +          <BFormInput
Done!

2021-03-19 12:46 UTC, JamesSCBD commented on components/register/steps/Search.vue
> +          <BFormInput
Done!

2021-03-19 12:46 UTC, JamesSCBD commented on components/register/steps/Search.vue
> +              <CButton v-if="data.item.nominated" color="secondary">
Done!

2021-03-19 12:46 UTC, JamesSCBD commented on components/list/ParticipantList.vue
> +        <RegistrationStatusCol v-if="data.item.registrationStatuses" :key="column.key" :registration-status="data.item.registrationStatuses[index] || {}" />
Used another column component.

2021-03-25 01:06 UTC, sbilodeau requested changes

2021-03-25 01:06 UTC, sbilodeau commented on components/register/steps/ContactInfo.vue
> +];
create a ~/data folder and put this list in ~/data/contact-titles.js and use it in all places

2021-03-25 01:06 UTC, sbilodeau commented on components/register/steps/ContactInfo.vue
> +              v-model="contactObj.phones[0]"
since we created the field for mutiple addres please use it

2021-03-25 01:06 UTC, sbilodeau commented on components/register/steps/Registration.vue
> +];
export to ~/data

2021-03-25 01:06 UTC, sbilodeau commented on components/register/steps/Registration.vue
> +        },
load from conference

2021-03-25 01:06 UTC, sbilodeau commented on pages/register/index.vue
> +      organizationId   : '00000000536a9b659973fc0d14cc9985',
```suggestion
```

2021-03-25 01:06 UTC, sbilodeau commented on pages/register/index.vue
> +  query.organizationIds               = [ this.organizationId ];
```suggestion
  query.organizationIds               = [ '00000000536a9b659973fc0d14cc9985' ];
```

2021-04-02 02:01 UTC, sbilodeau requested changes

2021-04-03 12:27 UTC, JamesSCBD commented on components/register/NominationCard.vue
> +];
Done!

2021-04-03 12:27 UTC, JamesSCBD commented on components/register/NominationCard.vue
> +            && nominationObj.limits.tags[tag]"
Done!

2021-04-03 12:27 UTC, JamesSCBD commented on components/register/NominationCard.vue
> +          {{ tag }}
Done!

2021-04-03 12:27 UTC, JamesSCBD commented on components/register/NominationCard.vue
> +          {{ `(${nominationObj.statistics.tags[tag]}/${nominationObj.limits.tags[tag]})` }}
Done!

2021-04-03 12:27 UTC, JamesSCBD commented on components/register/NominationCard.vue
> +              && nominationObj.limits.tags[tag] <= nominationObj.statistics.tags[tag]"
Done!

2021-04-03 12:28 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +      majorEvents: 'conferences/majorEvents',
removed. as currently its not required.

2021-04-03 12:28 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +      removeNomination   : 'participants/removeNomination',
Done! Auth flow corrected. so we can access store actions now.

2021-04-03 12:28 UTC, JamesSCBD commented on components/register/steps/Search.vue
> +    ...mapActions({
Done! Auth flow corrected. so we can access store actions now.

2021-04-03 12:28 UTC, JamesSCBD commented on pages/register/index.vue
> +    ...mapGetters({
Done! Auth flow corrected. so we can access store getters now.

2021-04-03 12:28 UTC, JamesSCBD commented on pages/register/index.vue
> +    ...mapActions({
Done! Auth flow corrected. so we can access store actions now.

2021-04-03 12:29 UTC, JamesSCBD commented on components/register/steps/ContactAddress.vue
> +    ...mapActions({
Done! Auth flow corrected. so we can access store actions now.

2021-04-03 12:29 UTC, JamesSCBD commented on store/participants.js
> +    const api          = new KronosApi(() => `Bearer ${key}`);
Done! Auth flow corrected.

2021-04-05 01:03 UTC, sbilodeau commented on components/register/RegisterDialog.vue
> +      removeNomination   : 'participants/removeNomination',
good!

2021-04-05 01:07 UTC, sbilodeau reviewed
good

2021-04-05 04:47 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +function getStateMachine() {
Done!

2021-04-05 04:48 UTC, JamesSCBD commented on components/register/steps/ContactInfo.vue
> +            The system will automatically search for any close match within your organization.
Done!

2021-04-05 04:49 UTC, JamesSCBD commented on components/ContactCard.vue
> +        const regex = /[a-z][a-z-]*/;
Done!

2021-04-05 04:50 UTC, JamesSCBD commented on components/list/ParticipantList.vue
> +  return _d.remove(`${firstName} ${lastName}`);
Ok. Done!

2021-04-05 04:50 UTC, JamesSCBD commented on components/register/steps/Search.vue
> +import _d from 'diacritics';
ok, Done!

2021-04-05 04:52 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +          Prev
Done!

2021-04-05 05:06 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +        <CButton v-if="fsm.can('next') && !fsm.is('search')" color="primary" @click="fsm.next(contact)">
removed unwanted contact params from next method

2021-04-05 05:09 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +      if (!value) this.fsm.close();
No. Once the dialog hides, required to close() the statemachine. that was just done here.

2021-04-05 05:26 UTC, JamesSCBD commented on components/register/steps/ContactInfo.vue
> +];
Done!

2021-04-05 05:26 UTC, JamesSCBD commented on components/register/steps/Registration.vue
> +];
Done!

2021-04-05 05:29 UTC, JamesSCBD commented on components/register/steps/Registration.vue
> +        },
Ok

2021-04-05 05:32 UTC, JamesSCBD commented on pages/register/index.vue
> +      organizationId   : '00000000536a9b659973fc0d14cc9985',
Done!

2021-04-05 05:32 UTC, JamesSCBD commented on pages/register/index.vue
> +  query.organizationIds               = [ this.organizationId ];
Done!

2021-04-05 13:09 UTC, JamesSCBD commented on components/list/columns/MeetingRegistrationStatus.vue
> +    <!-- {{ registrationStatus.date | datetime }} -->
Done!

2021-04-05 13:10 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +        </CButton>
Done!

2021-04-05 13:10 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +    ],
Done!

2021-04-06 12:20 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +    />
Done!

2021-04-07 13:45 UTC, JamesSCBD commented on components/register/NominationCard.vue
> +          class="col-3 col-sm-2 text-right"
fixed at some extent.

2021-04-14 22:22 UTC, sbilodeau requested changes
There is not much error handlin g(try/catch)

We need also to have a better error page for online nomination. currently the layout switch to default layout which is not good. I will think about that

We will need to create the CBD institution header 
we will also make the institution header load from the domain prefix:
eg: `cbd`.kronos.net and the invitation will need to match the institution in the header too.

2021-04-14 22:22 UTC, sbilodeau commented on components/register/steps/Search.vue
> +              v-model="firstName"
Can you make search `firstName` and `lastName` different fields? when we click back it override the search with the one selected.

2021-04-14 22:22 UTC, sbilodeau commented on components/register/steps/Validate.vue
> +    ''    : 'Please select',
this is smart!

2021-04-14 22:22 UTC, sbilodeau commented on data/roles.js
> +export const roles = [  // Todo import from ~/data
can you rename to `nomination-roles.js`?

2021-04-14 22:22 UTC, sbilodeau commented on layouts/register.vue
> +        </CHeader>
can you make the header to scroll with the page? with no predefined height?

will be replaced by a dynamic component like:

```html
<div :is="institution"></div>
```

2021-04-14 22:22 UTC, sbilodeau commented on store/participants.js
> +  },
remove `commit` instead of `// eslint-disable-line no-unused-vars`

2021-04-14 22:22 UTC, sbilodeau commented on store/participants.js
> +  async queryEvents({ commit }, query) { // eslint-disable-line no-unused-vars
remove `commit` instead of `// eslint-disable-line no-unused-vars`

2021-04-14 22:22 UTC, sbilodeau commented on store/participants.js
> +  async getNominationDetails({ commit }, query) { // eslint-disable-line no-unused-vars
remove `commit` instead of `// eslint-disable-line no-unused-vars`

2021-04-14 22:22 UTC, sbilodeau commented on store/participants.js
> +  async getNominationStatus({ commit }, data) { // eslint-disable-line no-unused-vars
remove `commit` instead of `// eslint-disable-line no-unused-vars`

2021-04-14 22:22 UTC, sbilodeau commented on store/participants.js
> +  async addNomination({ commit }, data) { // eslint-disable-line no-unused-vars
remove `commit` instead of `// eslint-disable-line no-unused-vars`

2021-04-14 22:22 UTC, sbilodeau commented on store/participants.js
> +  async removeNomination({ commit }, data) { // eslint-disable-line no-unused-vars
remove `commit` instead of `// eslint-disable-line no-unused-vars`

2021-04-15 05:24 UTC, JamesSCBD commented on components/ContactCard.vue
> +    hidePicture: {
Done!

2021-04-15 05:24 UTC, JamesSCBD commented on api/kronos.js
> +  async getNominationDetails(query) {
Done!

2021-04-15 05:25 UTC, JamesSCBD commented on api/kronos.js
> +  async getNominationStatus({ eventId, contactId }) {
Removed function as currently it is not usable.

2021-04-15 05:31 UTC, JamesSCBD commented on components/list/columns/MeetingRegistrationStatusHeader.vue
> +      <CBadge
Done!

2021-04-15 05:34 UTC, JamesSCBD commented on components/list/columns/MeetingRegistrationStatusHeader.vue
> +function tagValue({ tags }, tag) {
Done!

2021-04-15 05:50 UTC, JamesSCBD commented on components/register/NominationCard.vue
> +                :disabled="(tagValue(limits, tag) || 0) <= (tagValue(statistics, tag) || 0)"
Done!

2021-04-15 05:50 UTC, JamesSCBD commented on components/register/NominationCard.vue
> +function tagValue({ tags }, tag) {
Done!

2021-04-15 05:53 UTC, JamesSCBD commented on data/roles.js
> +export const roles = [  // Todo import from ~/data
Done!

2021-04-15 05:53 UTC, JamesSCBD commented on store/participants.js
> +  },
Done!

2021-04-15 06:00 UTC, JamesSCBD commented on store/participants.js
> +  async queryEvents({ commit }, query) { // eslint-disable-line no-unused-vars
need to define first parameter mandatory as it is a context.. so replace commit with context and removed comment

2021-04-15 06:00 UTC, JamesSCBD commented on store/participants.js
> +  async getNominationDetails({ commit }, query) { // eslint-disable-line no-unused-vars
need to define first parameter mandatory as it is a context.. so replace commit with context and removed comment

2021-04-15 06:00 UTC, JamesSCBD commented on store/participants.js
> +  async getNominationStatus({ commit }, data) { // eslint-disable-line no-unused-vars
need to define first parameter mandatory as it is a context.. so replace commit with context and removed comment

2021-04-15 06:00 UTC, JamesSCBD commented on store/participants.js
> +  async removeNomination({ commit }, data) { // eslint-disable-line no-unused-vars
need to define first parameter mandatory as it is a context.. so replace commit with context and removed comment

2021-04-15 09:02 UTC, JamesSCBD commented on components/register/RegisterDialog.vue
> +}
Changed as you required.. Need to use timeout to close based on confirmation flag.

2021-04-19 20:25 UTC, randyhoulahan approved these changes

2021-04-19 20:52 UTC, merged